/**
 * Converts a structured analysis result object into natural, spoken-language
 * text suitable for the Web Speech API.
 *
 * Strips markdown, HTML, URLs, emoji, decorative icons, raw JSON, button text,
 * internal IDs, and database field names.
 *
 * Returns { text: string, lang: string }
 */

// ── Transition phrases per language ─────────────────────────────────
const TRANSITIONS = {
  English: {
    opening: 'Here is the analysis of your document.',
    docType: (t) => `The document type is: ${t}.`,
    summaryIntro: 'Here is the summary of your document.',
    riskLevel: (l) => `The overall risk level is ${l}.`,
    riskScore: (s) => `The risk score is ${s} out of 10.`,
    clausesIntro: 'The following clauses may require your attention.',
    prosIntro: (n) => `There are ${n} positive points in this document.`,
    proItem: (i, t) => `Positive point ${i}: ${t}.`,
    consIntro: (n) => `There are ${n} concerns or potential risks.`,
    conItem: (i, t) => `Concern ${i}: ${t}.`,
    adviceIntro: 'Here is the recommended action.',
    recommendedAction: 'Recommended action: ',
    disclaimer:
      'Please note: this analysis is generated by an AI system and is for informational purposes only. ' +
      'It does not constitute legal advice. Always consult a qualified professional before making legal decisions.',
  },
  Hindi: {
    opening: 'यहाँ आपके दस्तावेज़ का विश्लेषण है।',
    docType: (t) => `दस्तावेज़ का प्रकार है: ${t}।`,
    summaryIntro: 'यहाँ आपके दस्तावेज़ का सारांश है।',
    riskLevel: (l) => `कुल जोखिम स्तर ${l} है।`,
    riskScore: (s) => `जोखिम स्कोर 10 में से ${s} है।`,
    clausesIntro: 'निम्नलिखित खंडों पर आपका ध्यान आवश्यक हो सकता है।',
    prosIntro: (n) => `इस दस्तावेज़ में ${n} सकारात्मक बिंदु हैं।`,
    proItem: (i, t) => `सकारात्मक बिंदु ${i}: ${t}।`,
    consIntro: (n) => `${n} चिंताएँ या संभावित जोखिम हैं।`,
    conItem: (i, t) => `चिंता ${i}: ${t}।`,
    adviceIntro: 'यहाँ अनुशंसित कार्रवाई है।',
    recommendedAction: 'अनुशंसित कार्रवाई: ',
    disclaimer:
      'कृपया ध्यान दें: यह विश्लेषण एक AI प्रणाली द्वारा तैयार किया गया है और केवल सूचनात्मक उद्देश्यों के लिए है। ' +
      'यह कानूनी सलाह नहीं है। कानूनी निर्णय लेने से पहले हमेशा एक योग्य पेशेवर से परामर्श करें।',
  },
  Bengali: {
    opening: 'এখানে আপনার নথির বিশ্লেষণ রয়েছে।',
    docType: (t) => `নথির ধরন হলো: ${t}।`,
    summaryIntro: 'এখানে আপনার নথির সারসংক্ষেপ রয়েছে।',
    riskLevel: (l) => `সামগ্রিক ঝুঁকির মাত্রা হলো ${l}।`,
    riskScore: (s) => `ঝুঁকির স্কোর ১০ এর মধ্যে ${s}।`,
    clausesIntro: 'নিম্নলিখিত ধারাগুলিতে আপনার মনোযোগ প্রয়োজন হতে পারে।',
    prosIntro: (n) => `এই নথিতে ${n}টি ইতিবাচক পয়েন্ট রয়েছে।`,
    proItem: (i, t) => `ইতিবাচক পয়েন্ট ${i}: ${t}।`,
    consIntro: (n) => `${n}টি উদ্বেগ বা সম্ভাব্য ঝুঁকি রয়েছে।`,
    conItem: (i, t) => `উদ্বেগ ${i}: ${t}।`,
    adviceIntro: 'এখানে প্রস্তাবিত পদক্ষেপ রয়েছে।',
    recommendedAction: 'প্রস্তাবিত পদক্ষেপ: ',
    disclaimer:
      'দয়া করে মনে রাখবেন: এই বিশ্লেষণটি একটি AI সিস্টেম দ্বারা তৈরি এবং শুধুমাত্র তথ্যমূলক উদ্দেশ্যে। ' +
      'এটি আইনি পরামর্শ নয়। আইনি সিদ্ধান্ত নেওয়ার আগে সর্বদা একজন যোগ্য পেশাদারের সাথে পরামর্শ করুন।',
  },
};

// ── Translation Dictionaries for Metadata ────────────────────────────
const DICTIONARIES = {
  Hindi: {
    // Contract types
    'employment': 'रोजगार',
    'freelance': 'स्वतंत्र कार्य (फ्रिलांस)',
    'nda': 'गोपनीयता समझौता (NDA)',
    'service': 'सेवा',
    'lease': 'पट्टा (लीज)',
    'other': 'अन्य',
    'unknown': 'अज्ञात',
    
    // Risk levels
    'low': 'कम',
    'moderate': 'मध्यम',
    'medium': 'मध्यम',
    'high': 'उच्च',
    'critical': 'गंभीर',

    // Common clauses / keywords
    'auto-renew': 'स्वचालित नवीनीकरण',
    'automatic renewal': 'स्वचालित नवीनीकरण',
    'non-compete': 'गैर-प्रतिस्पर्धा',
    'non compete': 'गैर-प्रतिस्पर्धा',
    'penalty': 'जुर्माना',
    'penalties': 'जुर्माना',
    'liquidated damages': 'परिनिर्धारित हर्जाना',
    'indemnif': 'क्षतिपूर्ति',
    'indemnity': 'क्षतिपूर्ति',
    'indemnification': 'क्षतिपूर्ति',
    'unlimited liability': 'असीमित देयता',
    'irrevocable': 'अपरिवर्तनीय',
    'perpetual': 'सतत (हमेशा के लिए)',
    'exclusive': 'अनन्य (एक्सक्लूसिव)',
    'termination for convenience': 'सुविधा के लिए समाप्ति',
    'unilateral': 'एकतरफा',
    'waive': 'त्याग करना (छोड़ना)',
    'waiver': 'त्याग (छूट)',
    'arbitration': 'मध्यस्थता',
    'no refund': 'कोई वापसी नहीं',
    'non-refundable': 'गैर-वापसी योग्य',
    'intellectual property assignment': 'बौद्धिक संपदा का हस्तांतरण',
    'intellectual property': 'बौद्धिक संपदा',
    'ip ownership': 'बौद्धिक संपदा स्वामित्व',
    'confidentiality': 'गोपनीयता',
    'governing law': 'शासकीय कानून',
    'dispute resolution': 'विवाद समाधान',
    'payment terms': 'भुगतान की शर्तें',
    'forfeiture': 'जब्ती',
    'forfeiture clause': 'जब्ती खंड',
  },
  Bengali: {
    // Contract types
    'employment': 'চাকরি',
    'freelance': 'ফ্রিল্যান্স',
    'nda': 'গোপনীয়তা চুক্তি (NDA)',
    'service': 'পরিষেবা',
    'lease': 'ইজারা',
    'other': 'অন্যান্য',
    'unknown': 'অজানা',
    
    // Risk levels
    'low': 'কম',
    'moderate': 'মধ্যম',
    'medium': 'মধ্যম',
    'high': 'উচ্চ',
    'critical': 'গুরুতর',

    // Common clauses / keywords
    'auto-renew': 'স্বয়ংক্রিয় পুনর্নবীকরণ',
    'automatic renewal': 'স্বয়ংক্রিয় পুনর্নবীকরণ',
    'non-compete': 'অ-প্রতিযোগিতা',
    'non compete': 'অ-প্রতিযোগিতা',
    'penalty': 'জরিমানা',
    'penalties': 'জরিমানা',
    'liquidated damages': 'ক্ষতিপূরণ নির্ধারণ',
    'indemnif': 'ক্ষতিপূরণ',
    'indemnity': 'ক্ষতিপূরণ',
    'indemnification': 'ক্ষতিপূরণ',
    'unlimited liability': 'সীমাহীন দায়বদ্ধতা',
    'irrevocable': 'অপরিবর্তনীয়',
    'perpetual': 'স্থায়ী',
    'exclusive': 'একচেটিয়া',
    'termination for convenience': 'সুবিধাজনক সমাপ্তি',
    'unilateral': 'একতরফা',
    'waive': 'মওকুফ',
    'waiver': 'মওকুফ',
    'arbitration': 'সালিশি',
    'no refund': 'অফেরতযোগ্য',
    'non-refundable': 'অফেরতযোগ্য',
    'intellectual property assignment': 'বুদ্ধিবৃত্তিক সম্পত্তি হস্তান্তর',
    'intellectual property': 'বুদ্ধিবৃত্তিক সম্পত্তি',
    'ip ownership': 'বুদ্ধিবৃত্তিক সম্পত্তি মালিকানা',
    'confidentiality': 'গোপনীয়তা',
    'governing law': 'পরিচালনাকারী আইন',
    'dispute resolution': 'বিরোধ নিষ্পত্তি',
    'payment terms': 'পেমেন্ট শর্তাবলী',
    'forfeiture': 'বাজেয়াপ্তকরণ',
    'forfeiture clause': 'বাজেয়াপ্তকরণ ধারা',
  }
};

// ── BCP-47 language tags ───────────────────────────────────────────
const LANG_TAGS = {
  English: 'en-IN',
  Hindi: 'hi-IN',
  Bengali: 'bn-IN',
};

/**
 * Remove noise that should never be spoken.
 */
function cleanText(raw) {
  if (!raw || typeof raw !== 'string') return '';
  return raw
    // Remove HTML tags
    .replace(/<[^>]*>/g, '')
    // Remove markdown bold/italic/strikethrough
    .replace(/(\*{1,3}|_{1,3}|~{2})/g, '')
    // Remove markdown headings
    .replace(/^#{1,6}\s+/gm, '')
    // Remove markdown links  [text](url) → text
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    // Remove standalone URLs
    .replace(/https?:\/\/[^\s)]+/g, '')
    // Remove common emoji / decorative chars
    .replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE00}-\u{FE0F}\u{200D}]/gu, '')
    // Remove leading bullets / dashes
    .replace(/^[\s]*[-•●▸▹►◆]\s*/gm, '')
    // Collapse multiple spaces / newlines
    .replace(/\s{2,}/g, ' ')
    .trim();
}

/**
 * Helper to translate terms to Hindi/Bengali if a dictionary entry exists
 */
function translateTerm(term, langName) {
  if (!term || typeof term !== 'string') return '';
  const langDict = DICTIONARIES[langName];
  if (!langDict) return cleanText(term);

  const key = term.trim().toLowerCase();
  if (langDict[key]) {
    return langDict[key];
  }

  // Fallback to substring matching (e.g. "forfeiture clause" matches "forfeiture")
  for (const [engKeyword, localTranslation] of Object.entries(langDict)) {
    if (key.includes(engKeyword)) {
      return localTranslation;
    }
  }

  return cleanText(term);
}

/**
 * Extract plain text from a pro/con item (can be string or {clause, explanation, advice}).
 */
function extractProConText(item, tr, langName) {
  if (typeof item === 'string') return cleanText(item);
  const parts = [];
  if (item.clause) parts.push(translateTerm(item.clause, langName));
  if (item.explanation) parts.push(cleanText(item.explanation));
  if (item.advice) parts.push(tr.recommendedAction + cleanText(item.advice));
  return parts.join('. ');
}

/**
 * Sniffs the character set to detect if text is Bengali or Hindi.
 */
function detectTextLanguage(text) {
  if (!text || typeof text !== 'string') return null;
  // Bengali Unicode range: \u0980-\u09FF
  if (/[\u0980-\u09FF]/.test(text)) {
    return 'Bengali';
  }
  // Devanagari (Hindi) Unicode range: \u0900-\u097F
  if (/[\u0900-\u097F]/.test(text)) {
    return 'Hindi';
  }
  return null;
}

/**
 * Resolve the language name to use. Prefers the explicit `language` parameter
 * passed from the upload form; falls back to sniffing the result object.
 */
function resolveLanguage(language, result) {
  // 1. Explicit language from upload form (English / Hindi / Bengali)
  if (language && TRANSITIONS[language]) return language;

  // 2. Try to detect from result.meta
  const metaLang = result?.meta?.language;
  if (metaLang && TRANSITIONS[metaLang]) return metaLang;

  // 3. Try to sniff from result content text (summary or overallAdvice)
  let sampleText = '';
  if (result?.overallAdvice) {
    sampleText += result.overallAdvice;
  }
  if (result?.summary) {
    if (Array.isArray(result.summary)) {
      sampleText += ' ' + result.summary.join(' ');
    } else if (typeof result.summary === 'string') {
      sampleText += ' ' + result.summary;
    }
  }
  const detected = detectTextLanguage(sampleText);
  if (detected) return detected;

  // 4. Fallback: try to detect from result metadata fields
  const raw = (result?.language || result?.preferredLanguage || '').toLowerCase();
  if (raw.includes('hindi')) return 'Hindi';
  if (raw.includes('bengali') || raw.includes('bangla')) return 'Bengali';
  return 'English';
}

/**
 * Build the complete speech script from the analysis result.
 *
 * @param {object} result   – The structured analysis result from the AI
 * @param {string} language – The language selected during upload (English/Hindi/Bengali)
 * @returns {{ text: string, lang: string }}
 */
export function buildSpeechText(result, language) {
  if (!result) return { text: '', lang: 'en-IN' };

  const langName = resolveLanguage(language, result);
  const tr = TRANSITIONS[langName];
  const langTag = LANG_TAGS[langName] || 'en-IN';
  const sections = [];

  // ── Opening ──────────────────────────────────────────────────────
  sections.push(tr.opening);

  // ── Document type ────────────────────────────────────────────────
  if (result.contractType) {
    sections.push(tr.docType(translateTerm(result.contractType, langName)));
  }

  // ── Summary ──────────────────────────────────────────────────────
  if (result.summary) {
    sections.push(tr.summaryIntro);
    if (Array.isArray(result.summary)) {
      sections.push(result.summary.map(cleanText).filter(Boolean).join(' '));
    } else {
      sections.push(cleanText(result.summary));
    }
  }

  // ── Risk score ───────────────────────────────────────────────────
  if (result.riskScore) {
    const score = result.riskScore.score;
    const label = result.riskScore.label;
    if (label) {
      sections.push(tr.riskLevel(translateTerm(label, langName)));
    }
    if (score !== undefined && score !== null) {
      sections.push(tr.riskScore(score));
    }
  }

  // ── Detected keywords / flagged clauses ──────────────────────────
  if (result.riskScore?.detectedKeywords?.length > 0) {
    sections.push(tr.clausesIntro);
    result.riskScore.detectedKeywords.forEach((kw) => {
      sections.push(translateTerm(kw, langName) + '.');
    });
  }

  // ── Pros (positive points) ──────────────────────────────────────
  if (result.pros?.length > 0) {
    sections.push(tr.prosIntro(result.pros.length));
    result.pros.forEach((pro, i) => {
      sections.push(tr.proItem(i + 1, extractProConText(pro, tr, langName)));
    });
  }

  // ── Cons (concerns / red flags) ─────────────────────────────────
  if (result.cons?.length > 0) {
    sections.push(tr.consIntro(result.cons.length));
    result.cons.forEach((con, i) => {
      sections.push(tr.conItem(i + 1, extractProConText(con, tr, langName)));
    });
  }

  // ── AI recommendation ───────────────────────────────────────────
  if (result.overallAdvice) {
    sections.push(tr.adviceIntro);
    sections.push(cleanText(result.overallAdvice));
  }

  // ── Legal disclaimer ────────────────────────────────────────────
  sections.push(tr.disclaimer);

  return {
    text: sections.join(' '),
    lang: langTag,
  };
}
